## SPDX-FileCopyrightText: 2023 Open Networking Foundation <info@opennetworking.org>
##
## SPDX-License-Identifier: Apache-2.0
##
info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  sbi: # Service Based Interface
    scheme: http
    registerIPv4: udr
    bindingIPv4: 0.0.0.0
    port: 8000
    tls: # the local path of TLS key
      key: /var/run/certs/udr.key # UDR TLS Private key
      pem: /var/run/certs/udr.crt # UDR TLS Certificate
  mongodb:
    name: aether
    url: "mongodb://mongodb:27017"  # URL de conexión con credenciales y host:puerto
  nrfUri: http://nrf:8000
  webuiUri: http://webui:5001

logger:
  UDR:
    debugLevel: info
    ReportCaller: false
