info:
  version: 1.0.0
  description: NSSF initial local configuration
configuration:
  nssfName: NSSF
  nrfUri: http://nrf:8000
  webuiUri: http://webui:5001
  sbi:
    scheme: http
    bindingIPv4: "0.0.0.0"
    registerIPv4: nssf
    tls:
      pem: /var/run/certs/tls.crt
      key: /var/run/certs/tls.key
  serviceNameList:
    - nnssf-nsselection
    - nnssf-nssaiavailability
  nsiList:
    - snssai:
        sst: 1
        sd: "010203"
      nsiInformationList:
        - nrfId: http://nrf:8000/nnrf-nfm/v1/nf-instances
          nsiId: 22