## SPDX-FileCopyrightText: 2023 Open Networking Foundation <info@opennetworking.org>
##
## SPDX-License-Identifier: Apache-2.0
##
info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  sbi: # Service Based Interface
    scheme: http
    registerIPv4: 172.28.0.9
    bindingIPv4: 172.28.0.9
    port: 8000
  mongodb:
    name: aether
    url: http://dummy
    authKeysDbName: authentication
    authUrl: http://dummy
