## SPDX-FileCopyrightText: 2023 Open Networking Foundation <info@opennetworking.org>
##
## SPDX-License-Identifier: Apache-2.0
##
info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  sbi: # Service Based Interface
    scheme: https
    registerIPv4: 172.28.0.9
    bindingIPv4: 172.28.0.9
    port: 8000
    tls: # the local path of TLS key
      key: /var/run/tls.key # UDR TLS Certificate
      pem: /var/run/tls.crt # UDR TLS Private key
  mongodb:
    name: aether
    url: "mongodb://172.28.0.30:27017"  # URL de conexión con credenciales y host:puerto
  nrfUri: https://172.28.0.4:8000
  webuiUri: https://172.28.0.11:5000

logger:
  UDR:
    debugLevel: debug
    ReportCaller: false
